# Generated by Django 4.2.2 on 2023-08-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='first name')),
                ('lname', models.CharField(max_length=50, verbose_name='last name')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('bdate', models.DateTimeField(verbose_name='birth date')),
            ],
        ),
    ]
