# Generated by Django 4.2.2 on 2023-09-16 20:42

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=home.models.change_img_name),
        ),
    ]
