# Generated by Django 4.2.2 on 2023-09-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='github_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='instagram_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='linkedin_link',
            field=models.URLField(null=True),
        ),
    ]
