# Generated by Django 4.2.2 on 2023-09-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_thumbnail_article_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('project', 'Project'), ('article', 'Article'), ('person', 'Person')], max_length=50, null=True),
        ),
    ]
