# Generated by Django 4.2.2 on 2023-08-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bdate',
            field=models.DateField(verbose_name='birth date'),
        ),
    ]
