# Generated by Django 4.2.2 on 2023-09-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('project', 'Project'), ('article', 'Article'), ('person', 'Person')], default='Article', max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='person',
            name='img',
        ),
        migrations.AddField(
            model_name='person',
            name='img',
            field=models.ManyToManyField(blank=True, to='home.image'),
        ),
    ]
