# Generated by Django 4.2.2 on 2023-08-28 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_person_bdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateField(null=True, verbose_name='Careted At'),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.person'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=50, null=True)),
                ('university', models.CharField(max_length=50, null=True)),
                ('started_at', models.DateField(null=True)),
                ('ended_at', models.DateField(null=True)),
                ('img', models.ImageField(null=True, upload_to='uploads/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.person')),
            ],
        ),
    ]
