# Generated by Django 4.2.2 on 2023-09-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_image_type_remove_person_img_person_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='photos',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='img',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='img',
            new_name='images',
        ),
    ]
