# Generated by Django 4.2.2 on 2023-08-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_project_created_at_alter_project_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='img',
            field=models.ImageField(null=True, upload_to='media/person/'),
        ),
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ImageField(null=True, upload_to='media/project/'),
        ),
        migrations.AlterField(
            model_name='education',
            name='img',
            field=models.ImageField(null=True, upload_to='media/education/'),
        ),
    ]
