# Generated by Django 4.2.2 on 2023-09-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bdate',
            field=models.DateField(null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
    ]
