# Generated by Django 4.2.2 on 2023-09-07 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_person_bdate_alter_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='img',
            field=models.ImageField(null=True, upload_to='education/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.ImageField(null=True, upload_to='person/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(null=True, upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='img',
            field=models.ImageField(null=True, upload_to='skill/'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('img', models.FileField(null=True, upload_to='article/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.person')),
            ],
        ),
    ]
