# Generated by Django 4.2.2 on 2023-09-07 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_education_img_alter_person_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('article', 'Artcile'), ('eduction', 'Education'), ('project', 'Project'), ('person', 'Person')], default=1, max_length=20)),
                ('img', models.ImageField(upload_to=models.CharField(choices=[('article', 'Artcile'), ('eduction', 'Education'), ('project', 'Project'), ('person', 'Person')], default=1, max_length=20))),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='img',
        ),
        migrations.RemoveField(
            model_name='education',
            name='img',
        ),
        migrations.RemoveField(
            model_name='person',
            name='img',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='img',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.AddField(
            model_name='person',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
