# Generated by Django 4.2.2 on 2023-09-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_article_user_remove_education_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='article',
        ),
        migrations.RemoveField(
            model_name='person',
            name='education',
        ),
        migrations.RemoveField(
            model_name='person',
            name='project',
        ),
        migrations.RemoveField(
            model_name='person',
            name='skill',
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='education',
            field=models.ManyToManyField(blank=True, to='home.education'),
        ),
        migrations.AddField(
            model_name='person',
            name='project',
            field=models.ManyToManyField(blank=True, to='home.project'),
        ),
        migrations.AddField(
            model_name='person',
            name='skill',
            field=models.ManyToManyField(blank=True, to='home.skill'),
        ),
    ]
