# Generated by Django 4.2.2 on 2023-09-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_person_article_remove_person_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='article',
            field=models.ManyToManyField(blank=True, to='home.article'),
        ),
    ]
