# Generated by Django 4.2.2 on 2023-09-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_person_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
