# Generated by Django 4.2.2 on 2023-09-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_article_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='images',
            name='type',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='person/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
