# Generated by Django 4.2.2 on 2023-09-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_description_article_summary_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
