# Generated by Django 4.2.2 on 2023-09-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_article_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='img',
        ),
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ManyToManyField(blank=True, to='home.image'),
        ),
    ]
