# Generated by Django 4.2.2 on 2023-09-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_article_thumbnail_alter_person_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='person/'),
        ),
    ]
