# Generated by Django 4.2.2 on 2023-09-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_education_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='img',
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/'),
        ),
        migrations.AlterField(
            model_name='education',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='education/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
