# Generated by Django 4.2.2 on 2023-09-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_article_img_alter_article_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='article/thumbnail/'),
        ),
    ]
